services:
  app:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    image: ghcr.io/mrmodest/reisenotiz:edge-amd64 # change to `edge-arm64` for ARM64
    ports:
      - '8080:8080'
    # Uncomment to run with custom UID/GID
    # user: "1000:1000"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
