import {
  ArrowLeft,
  Ban,
  Bed,
  Bookmark,
  Calendar,
  CalendarFold,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  CircleQuestionMark,
  CircleX,
  Clock4,
  IdCard,
  Inbox,
  Info,
  House,
  LoaderCircle,
  Luggage,
  MapIcon,
  MapPin,
  Moon,
  MoveRight,
  Orbit,
  PanelLeft,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  RefreshCw,
  Save,
  Search,
  Settings,
  ShieldQuestionMark,
  SquareArrowRightEnter,
  SquareArrowRightExit,
  SquarePen,
  Sun,
  TicketsPlane,
  Train,
  Trash2,
  TriangleAlert,
  User,
  X,
  type LucideIcon,
} from 'lucide-react'

const icons = {
  'arrow-right': MoveRight,
  'back': ArrowLeft,
  'home': House,
  'inbox': Inbox,
  'settings': Settings,
  'light-theme': Sun,
  'dark-theme': Moon,
  'document': Paperclip,
  'close': CircleX,
  'luggage': Luggage,
  'boarding': Orbit,
  'flight': Plane,
  'flight-departure': PlaneTakeoff,
  'flight-arrival': PlaneLanding,
  'hotel-checkIn': SquareArrowRightEnter,
  'hotel-checkOut': SquareArrowRightExit,
  'map-pin': MapPin,
  'trip': TicketsPlane,
  'flight-checkin': IdCard,
  'check-circle': CircleCheck,
  'warning': TriangleAlert,
  'time': Clock4,
  'calendar': Calendar,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'circle-alert': CircleAlert,
  'menu': PanelLeft,
  'sidebar-close': PanelLeftClose,
  'sidebar-open': PanelLeftOpen,
  'bookmark': Bookmark,
  'no-data': CircleQuestionMark,
  'loader': LoaderCircle,
  'logo': MapIcon,
  'timeline': CalendarFold,
  'edit': SquarePen,
  'save': Save,
  'cancel': Ban,
  'search': Search,
  'check': Check,
  'add': CirclePlus,
  'car': Car,
  'train': Train,
  'accommodation': Bed,
  'trash': Trash2,
  'chevron-down': ChevronDown,
  'x': X,
  'person': User,
  'attachment': Paperclip,
  'info': Info,
  'unknown': ShieldQuestionMark,
  'refresh': RefreshCw,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof icons

export function Icon({ name, className }: { name: IconName; className?: string }) {
  const Component = icons[name]
  return <Component className={className} />
}
